# INVENTARIO DE SEVIDORES DE DATACENTER PANDO
# ===========================================
#
# Directrices para mantener el orden del inventario:
# - formato yaml
# - servicios ordenados alfabeticamente
# - todos los servicios deben tener al menos 1 ambiente con escepción de STP
# - ambientes ordenados por orden de despliegue (ej.: desa->test->prep->prod)
# - hosts ordenados alfabeticamente
# - cuanto se actualice agregar en el commit comentario de lo que se agregó
#

pando:
  children:
    amp:
      children:
        amp_test:
          hosts:
            amp-testing-1.pando.mgmt.sva.antel.com.uy:
            amp-testing-2.pando.mgmt.sva.antel.com.uy:
        amp_prep:
          hosts:
            app01.amp.prep.pando.mgmt.sva.antel.com.uy:
            app02.amp.prep.pando.mgmt.sva.antel.com.uy:
            app03.amp.prep.pando.mgmt.sva.antel.com.uy:
        amp_prod:
          hosts:
            gestor1.amp.prod.pando.mgmt.sva.antel.com.uy:
            gestor2.amp.prod.pando.mgmt.sva.antel.com.uy:
            gestor3.amp.prod.pando.mgmt.sva.antel.com.uy:
            gestor4.amp.prod.pando.mgmt.sva.antel.com.uy:
            gestor5.amp.prod.pando.mgmt.sva.antel.com.uy:
            gestor6.amp.prod.pando.mgmt.sva.antel.com.uy:

    apiveratv:
      children:
        apiveratv_prod:
          hosts:
            fe01.apiveratv.prod.pando.mgmt.sva.antel.com.uy:
            fe02.apiveratv.prod.pando.mgmt.sva.antel.com.uy:
            fe03.apiveratv.prod.pando.mgmt.sva.antel.com.uy:
            fe04.apiveratv.prod.pando.mgmt.sva.antel.com.uy:
            fe05.apiveratv.prod.pando.mgmt.sva.antel.com.uy:

    autorizador:
      children:
        autorizador_test:
          hosts:
            ws01.autorizador.test.pando.mgmt.sva.antel.com.uy:
        autorizador_prep:
          hosts:
            ws01.autorizador.prep.pando.mgmt.sva.antel.com.uy:
        autorizador_prod:
          hosts:
            ws01.autorizador.prod.pando.mgmt.sva.antel.com.uy:
            ws02.autorizador.prod.pando.mgmt.sva.antel.com.uy:

    busman:
      children:
        busman_prep:
          hosts:
            app01.busman.prep.pando.mgmt.sva.antel.com.uy: 
            app02.busman.prep.pando.mgmt.sva.antel.com.uy: 
        busman_prod:
          hosts:
            app01.busman.prod.pando.mgmt.sva.antel.com.uy:
            app02.busman.prod.pando.mgmt.sva.antel.com.uy:
            app03.busman.prod.pando.mgmt.sva.antel.com.uy:
            app04.busman.prod.pando.mgmt.sva.antel.com.uy:
            ftp01.busman.prod.pando.mgmt.sva.antel.com.uy:

    cds_assets:
      children:
        cds_assetes_test:
          hosts:
            app01.assets.test.pando.mgmt.sva.antel.com.uy:
        cds_assetes_prep:
          hosts:
            app01.assets.prep.pando.mgmt.sva.antel.com.uy:
        cds_assetes_prod:
          hosts:
            app01.assets.prod.pando.mgmt.sva.antel.com.uy:
            app02.assets.prod.pando.mgmt.sva.antel.com.uy:
    
    cds_core:
      children:
        cds_core_test:
          hosts:
            core01-deb11.cds.test.pando.mgmt.sva.antel.com.uy:
            core02-deb11.cds.test.pando.mgmt.sva.antel.com.uy:
        cds_core_prep:
          hosts:
            core01-deb11.cds.prep.pando.mgmt.sva.antel.com.uy:
            core02-deb11.cds.prep.pando.mgmt.sva.antel.com.uy:
        cds_core_prod:
          hosts:
            core01-deb11.cds.prod.pando.mgmt.sva.antel.com.uy:
            core02-deb11.cds.prod.pando.mgmt.sva.antel.com.uy:
            core03-deb11.cds.prod.pando.mgmt.sva.antel.com.uy:
    
    cds_frontend:
      children:
        cds_frontend_test:
          hosts:
            frontend01-deb11.cds.test.pando.mgmt.sva.antel.com.uy:
            frontend02-deb11.cds.test.pando.mgmt.sva.antel.com.uy:
        cds_frontend_prep:
          hosts:
            frontend01-deb11.cds.prep.pando.mgmt.sva.antel.com.uy:
            frontend02-deb11.cds.prep.pando.mgmt.sva.antel.com.uy:
            frontend03-deb11.cds.prep.pando.mgmt.sva.antel.com.uy:
        cds_frontend_prod:
          hosts:
            frontend01-deb11.cds.prod.pando.mgmt.sva.antel.com.uy:
            frontend02-deb11.cds.prod.pando.mgmt.sva.antel.com.uy:
            frontend03-deb11.cds.prod.pando.mgmt.sva.antel.com.uy:
            frontend04-deb11.cds.prod.pando.mgmt.sva.antel.com.uy:
            frontend05-deb11.cds.prod.pando.mgmt.sva.antel.com.uy:
            frontend06-deb11.cds.prod.pando.mgmt.sva.antel.com.uy:
            frontend07-deb11.cds.prod.pando.mgmt.sva.antel.com.uy:
            frontend08-deb11.cds.prod.pando.mgmt.sva.antel.com.uy:
            frontend09-deb11.cds.prod.pando.mgmt.sva.antel.com.uy:
            frontend10-deb11.cds.prod.pando.mgmt.sva.antel.com.uy:
            frontend11-deb11.cds.prod.pando.mgmt.sva.antel.com.uy:
            frontend12-deb11.cds.prod.pando.mgmt.sva.antel.com.uy:
            frontend13-deb11.cds.prod.pando.mgmt.sva.antel.com.uy:
            frontend14-deb11.cds.prod.pando.mgmt.sva.antel.com.uy:
            frontend15-deb11.cds.prod.pando.mgmt.sva.antel.com.uy:
            frontend16-deb11.cds.prod.pando.mgmt.sva.antel.com.uy:
            frontend17-deb11.cds.prod.pando.mgmt.sva.antel.com.uy:
            frontend18-deb11.cds.prod.pando.mgmt.sva.antel.com.uy:
            frontend19-deb11.cds.prod.pando.mgmt.sva.antel.com.uy:
            frontend20-deb11.cds.prod.pando.mgmt.sva.antel.com.uy:
            frontend21-deb11.cds.prod.pando.mgmt.sva.antel.com.uy:
            frontend22-deb11.cds.prod.pando.mgmt.sva.antel.com.uy:
            frontend23-deb11.cds.prod.pando.mgmt.sva.antel.com.uy:
            frontend24-deb11.cds.prod.pando.mgmt.sva.antel.com.uy:
            frontend25-deb11.cds.prod.pando.mgmt.sva.antel.com.uy:
            frontend26-deb11.cds.prod.pando.mgmt.sva.antel.com.uy:
            frontend27-deb11.cds.prod.pando.mgmt.sva.antel.com.uy:
            frontend28-deb11.cds.prod.pando.mgmt.sva.antel.com.uy:
            frontend29-deb11.cds.prod.pando.mgmt.sva.antel.com.uy:
            frontend30-deb11.cds.prod.pando.mgmt.sva.antel.com.uy:
            frontend31-deb11.cds.prod.pando.mgmt.sva.antel.com.uy:
    
    cds_portal:
      children:
        cds_portal_test:
          hosts:
            portal01.cds.test.pando.mgmt.sva.antel.com.uy:
        cds_portal_prep:
          hosts:
            portal01.cds.prep.pando.mgmt.sva.antel.com.uy:
            portal02.cds.prep.pando.mgmt.sva.antel.com.uy:
        cds_portal_prod:
          hosts:
            portal01.cds.prod.pando.mgmt.sva.antel.com.uy:
            portal02.cds.prod.pando.mgmt.sva.antel.com.uy:
    
    cds_seguimiento:
      children:
        cds_seguimiento_test:
          hosts:
            seguimiento01.cds.test.pando.mgmt.sva.antel.com.uy:
            seguimiento02.cds.test.pando.mgmt.sva.antel.com.uy:
            seguimiento03.cds.test.pando.mgmt.sva.antel.com.uy:
            seguimiento04.cds.test.pando.mgmt.sva.antel.com.uy:
            seguimiento05.cds.test.pando.mgmt.sva.antel.com.uy:
            seguimiento06.cds.test.pando.mgmt.sva.antel.com.uy:
            seguimiento07.cds.test.pando.mgmt.sva.antel.com.uy:
            seguimiento08.cds.test.pando.mgmt.sva.antel.com.uy:
        cds_seguimiento_prep:
          hosts:
            seguimiento01.cds.prep.pando.mgmt.sva.antel.com.uy:
            seguimiento02.cds.prep.pando.mgmt.sva.antel.com.uy:
            seguimiento03.cds.prep.pando.mgmt.sva.antel.com.uy:
            seguimiento04.cds.prep.pando.mgmt.sva.antel.com.uy:
            seguimiento05.cds.prep.pando.mgmt.sva.antel.com.uy:
            seguimiento06.cds.prep.pando.mgmt.sva.antel.com.uy:
            seguimiento07.cds.prep.pando.mgmt.sva.antel.com.uy:
            seguimiento08.cds.prep.pando.mgmt.sva.antel.com.uy:
            seguimiento09.cds.prep.pando.mgmt.sva.antel.com.uy:
            seguimiento10.cds.prep.pando.mgmt.sva.antel.com.uy:
        cds_seguimiento_prod:
          hosts:
            seguimiento01.cds.prod.pando.mgmt.sva.antel.com.uy:
            seguimiento02.cds.prod.pando.mgmt.sva.antel.com.uy:
            seguimiento03.cds.prod.pando.mgmt.sva.antel.com.uy:
            seguimiento04.cds.prod.pando.mgmt.sva.antel.com.uy:
            seguimiento05.cds.prod.pando.mgmt.sva.antel.com.uy:
            seguimiento06.cds.prod.pando.mgmt.sva.antel.com.uy:
            seguimiento07.cds.prod.pando.mgmt.sva.antel.com.uy:
            seguimiento08.cds.prod.pando.mgmt.sva.antel.com.uy:
            seguimiento09.cds.prod.pando.mgmt.sva.antel.com.uy:
            seguimiento10.cds.prod.pando.mgmt.sva.antel.com.uy:
            seguimiento11.cds.prod.pando.mgmt.sva.antel.com.uy:
            seguimiento12.cds.prod.pando.mgmt.sva.antel.com.uy:
            seguimiento13.cds.prod.pando.mgmt.sva.antel.com.uy:
            seguimiento14.cds.prod.pando.mgmt.sva.antel.com.uy:
            seguimiento15.cds.prod.pando.mgmt.sva.antel.com.uy:
            seguimiento16.cds.prod.pando.mgmt.sva.antel.com.uy:
            seguimiento17.cds.prod.pando.mgmt.sva.antel.com.uy:
            seguimiento18.cds.prod.pando.mgmt.sva.antel.com.uy:
            seguimiento19.cds.prod.pando.mgmt.sva.antel.com.uy:
            seguimiento20.cds.prod.pando.mgmt.sva.antel.com.uy:
            seguimiento21.cds.prod.pando.mgmt.sva.antel.com.uy:
            seguimiento22.cds.prod.pando.mgmt.sva.antel.com.uy:
            seguimiento23.cds.prod.pando.mgmt.sva.antel.com.uy:
            seguimiento24.cds.prod.pando.mgmt.sva.antel.com.uy:
            seguimiento25.cds.prod.pando.mgmt.sva.antel.com.uy:
            seguimiento26.cds.prod.pando.mgmt.sva.antel.com.uy:
    
    cds_sesiones:
      children:
        cds_sesiones_prep:
          hosts:
            sesiones01.cds.prep.pando.mgmt.sva.antel.com.uy:
        cds_sesiones_prod:
          hosts:
            sesiones01.cds.prod.pando.mgmt.sva.antel.com.uy:
            sesiones02.cds.prod.pando.mgmt.sva.antel.com.uy:
            sesiones03.cds.prod.pando.mgmt.sva.antel.com.uy:
    
    cds_webexample:
      children:
        cds_webexample_test:
          hosts:
            webexample01.cds.test.pando.mgmt.sva.antel.com.uy:
        cds_webexample_prep:
          hosts:
            webexample01.cds.prep.pando.mgmt.sva.antel.com.uy:
        cds_webexample_prod:
          hosts:
            webexample01.cds.prod.pando.mgmt.sva.antel.com.uy:

    cutaplay:
      children:
        cutaplay_test:
          hosts:
            app01.cutaplay.test.pando.mgmt.sva.antel.com.uy:
        cutaplay_prep:
          hosts:
            app01.cutaplay.prep.pando.mgmt.sva.antel.com.uy:
        cutaplay_prod:
          hosts:
            app01.cutaplay.prod.pando.mgmt.sva.antel.com.uy:
            app02.cutaplay.prod.pando.mgmt.sva.antel.com.uy:
            app03.cutaplay.prod.pando.mgmt.sva.antel.com.uy:
            app04.cutaplay.prod.pando.mgmt.sva.antel.com.uy:
            app05.cutaplay.prod.pando.mgmt.sva.antel.com.uy:

    dnsbackend:
      children:
        dnsbackend_test:
          hosts:
            app01.dnsbackend.test.pando.mgmt.sva.antel.com.uy:

    elon:
      children:
        elon_prep:
          hosts:
            app01.elon.prep.pando.mgmt.sva.antel.com.uy:
            app02.elon.prep.pando.mgmt.sva.antel.com.uy:
        elon_prod:
          hosts:
            app01.elon.prod.pando.mgmt.sva.antel.com.uy:
            app02.elon.prod.pando.mgmt.sva.antel.com.uy:
            app03.elon.prod.pando.mgmt.sva.antel.com.uy:
            app04.elon.prod.pando.mgmt.sva.antel.com.uy:
            app05.elon.prod.pando.mgmt.sva.antel.com.uy:

#    lua:
#      children:
#        lua_prep:
#          hosts:
#            app01.lua.prep.pando.mgmt.sva.antel.com.uy:
#            app02.lua.prep.pando.mgmt.sva.antel.com.uy:
#            app03.lua.prep.pando.mgmt.sva.antel.com.uy:
#            app04.lua.prep.pando.mgmt.sva.antel.com.uy:
#            app05.lua.prep.pando.mgmt.sva.antel.com.uy:
#            app06.lua.prep.pando.mgmt.sva.antel.com.uy:
#            cache01.lua.prep.pando.mgmt.sva.antel.com.uy:
#            fw01.lua.prep.pando.mgmt.sva.antel.com.uy:
#            lb01.lua.prep.pando.mgmt.sva.antel.com.uy:
#            ldap01.lua.prep.pando.mgmt.sva.antel.com.uy:
#            mta01.lua.prep.pando.mgmt.sva.antel.com.uy:
#        lua_prod:
#          hosts:
#            app01.lua.prod.pando.mgmt.sva.antel.com.uy:
#            app02.lua.prod.pando.mgmt.sva.antel.com.uy:
#            app03.lua.prod.pando.mgmt.sva.antel.com.uy:
#            app04.lua.prod.pando.mgmt.sva.antel.com.uy:
#            app05.lua.prod.pando.mgmt.sva.antel.com.uy:
#            app06.lua.prod.pando.mgmt.sva.antel.com.uy:
#            cache01.lua.prod.pando.mgmt.sva.antel.com.uy:
#            cache02.lua.prod.pando.mgmt.sva.antel.com.uy:
#            #fw01.lua.prod.pando.mgmt.sva.antel.com.uy:
#            lb01.lua.prod.pando.mgmt.sva.antel.com.uy:
#            lb02.lua.prod.pando.mgmt.sva.antel.com.uy:
#            lb03.lua.prod.pando.mgmt.sva.antel.com.uy:
#            ldap01.lua.prod.pando.mgmt.sva.antel.com.uy:
#            ldap02.lua.prod.pando.mgmt.sva.antel.com.uy:
#            mta01.lua.prod.pando.mgmt.sva.antel.com.uy:


    lupitavera:
      children:
        lupitavera_test:
          hosts:
            elk01.lupitavera.test.pando.mgmt.sva.antel.com.uy:
            mic01.lupitavera.test.pando.mgmt.sva.antel.com.uy:
        lupitavera_prod:
          hosts:
            elk01.lupitavera.prod.pando.mgmt.sva.antel.com.uy:
            elk02.lupitavera.prod.pando.mgmt.sva.antel.com.uy:
            elk03.lupitavera.prod.pando.mgmt.sva.antel.com.uy:
            mic01.lupitavera.prod.pando.mgmt.sva.antel.com.uy:
            mic02.lupitavera.prod.pando.mgmt.sva.antel.com.uy:

    mautic:
      children:
        mautic_test:
          hosts:
            mautic01.test.pando.mgmt.sva.antel.com.uy:
        mautic_miantel_prod:
          hosts:
            app01.mautic-miantel.prod.pando.mgmt.sva.antel.com.uy:
        mautic_tickantel_prod:
          hosts:
            app01.mautic-tickantel.prod.pando.mgmt.sva.antel.com.uy:

    miantel-apiconfig:
      children:
        mliantel-apiconfig-prod:
          app01.miantel-apiconfig.prod.pando.mgmt.sva.antel.com.uy:
          app02.miantel-apiconfig.prod.pando.mgmt.sva.antel.com.uy:
          control01.miantel-apiconfig.prod.pando.mgmt.sva.antel.com.uy:
              
    nveratv:
      children:
        nveratv_prep:
          hosts:
            api01.apiveratv.prep.pando.mgmt.sva.antel.com.uy:
            api02.apiveratv.prep.pando.mgmt.sva.antel.com.uy:
            backend01.nveratv.prep.pando.mgmt.sva.antel.com.uy:
            backend02.nveratv.prep.pando.mgmt.sva.antel.com.uy:
            control01.apiveratv.prep.pando.mgmt.sva.antel.com.uy:
            web01.nveratv.prep.pando.mgmt.sva.antel.com.uy:
            web02.nveratv.prep.pando.mgmt.sva.antel.com.uy:
        nveratv_prod:
          hosts:
            backend01.nveratv.prod.pando.mgmt.sva.antel.com.uy:
            backend02.nveratv.prod.pando.mgmt.sva.antel.com.uy:
            control01.apiveratv.prod.pando.mgmt.sva.antel.com.uy:
            control02.apiveratv.prod.pando.mgmt.sva.antel.com.uy:
            web01.nveratv.prod.pando.mgmt.sva.antel.com.uy:
            web02.nveratv.prod.pando.mgmt.sva.antel.com.uy:

    stp:
      hosts:
        pando-bastion:
        app.vcontent.restore.pando.mgmt.sva.antel.com.uy:
        backups01.pando.mgmt.sva.antel.com.uy:
#        backups02.pando.mgmt.sva.antel.com.uy:
#        desarrollo17pan.pando.mgmt.sva.antel.com.uy:
        desarrollo18pan.pando.mgmt.sva.antel.com.uy:
        desarrollo19pan.pando.mgmt.sva.antel.com.uy:
        devops01.pando.mgmt.sva.antel.com.uy:
        gitlab01.pando.mgmt.sva.antel.com.uy:
#        gitlab02.pando.mgmt.sva.antel.com.uy:
        honey01.pando.mgmt.sva.antel.com.uy:
        jmeter1.pando.mgmt.sva.antel.com.uy:
        jmeter2.pando.mgmt.sva.antel.com.uy:
        jmeter3.pando.mgmt.sva.antel.com.uy:
        jmeter4.pando.mgmt.sva.antel.com.uy:
        kibana02.pando.mgmt.sva.antel.com.uy:
        ns1.pando.mgmt.sva.antel.com.uy:
        ns2.pando.mgmt.sva.antel.com.uy:
        nsin01.pando.mgmt.sva.antel.com.uy:
        nsin02.pando.mgmt.sva.antel.com.uy:
        pdc-lua.pando.mgmt.sva.antel.com.uy:
        pdc01.pando.mgmt.sva.antel.com.uy:
        pdc02.pando.mgmt.sva.antel.com.uy:
        pdc03.pando.mgmt.sva.antel.com.uy:
        plataforma.pando.mgmt.sva.antel.com.uy:
        proxy-noprod.pando.mgmt.sva.antel.com.uy:
        proxy01.prod.pando.mgmt.sva.antel.com.uy:
        proxy02.prod.pando.mgmt.sva.antel.com.uy:
        repos-testing.pando.mgmt.sva.antel.com.uy:
        repos-prod.pando.mgmt.sva.antel.com.uy:
        rocketeer.pando.mgmt.sva.antel.com.uy:
        rocketeer02.pando.mgmt.sva.antel.com.uy:
        rp01.pando.mgmt.sva.antel.com.uy:
        rp02.pando.mgmt.sva.antel.com.uy:
        stp01.pando.mgmt.sva.antel.com.uy:
#        template-centos.pando.mgmt.sva.antel.com.uy:
#        template-debian.pando.mgmt.sva.antel.com.uy:
#        template-debian11.pando.mgmt.sva.antel.com.uy:
#        wazuh-worker.pando.mgmt.sva.antel.com.uy:
        zabbix.pando.mgmt.sva.antel.com.uy:
        zabbix5.pando.mgmt.sva.antel.com.uy:

    restricciones:
      children:
        restricciones_test:
          hosts:
            app01.restriccion.test.pando.mgmt.sva.antel.com.uy:
        restricciones_prep:
          hosts:
            app01.restriccion.prep.pando.mgmt.sva.antel.com.uy:
            app02.restriccion.prep.pando.mgmt.sva.antel.com.uy:
        restricciones_prod:
          hosts:
            app01.restriccion.prod.pando.mgmt.sva.antel.com.uy:
            app02.restriccion.prod.pando.mgmt.sva.antel.com.uy:
            app03.restriccion.prod.pando.mgmt.sva.antel.com.uy:
            app04.restriccion.prod.pando.mgmt.sva.antel.com.uy:
    
    wilee:
      children:
        wilee_test:
          hosts:
            app01.wilee.test.pando.mgmt.sva.antel.com.uy:
            app02.wilee.test.pando.mgmt.sva.antel.com.uy:
            bkb01.wilee.test.pando.mgmt.sva.antel.com.uy:
            bkb02.wilee.test.pando.mgmt.sva.antel.com.uy:
            bkb03.wilee.test.pando.mgmt.sva.antel.com.uy:
        wilee_prod:
          hosts:
            app01.wilee.prod.pando.mgmt.sva.antel.com.uy:
            app02.wilee.prod.pando.mgmt.sva.antel.com.uy:
            bkb01.wilee.prod.pando.mgmt.sva.antel.com.uy:
            bkb02.wilee.prod.pando.mgmt.sva.antel.com.uy:
            bkb03.wilee.prod.pando.mgmt.sva.antel.com.uy:

