---
- name: Add_key_to_root
  hosts:
    #ndc-bacula
    #ndc-kibana
    pando-bastion
  become: true
  vars_files:
    - user_list.yml

  tasks:
  - name: "Add authorized keys"
    authorized_key:
      user: "root"
      state: present
      key: "{{ lookup('file', './inventories/user_public_keys/id_rsa_'+ item + '.pub') }}"
    with_items: "{{ users }}"

