---
- name: Add_ssh_users
  hosts:
    lezama-bastion
    #pando-bastion
    #jenkinsmobile.stp.prod.mgmt.sva.antel.com.uy
    #wilee_test
    #wilee_prod
  become: true
  vars_files:
    - pub_password.yml
    - user_list.yml
  gather_facts: true

  tasks:
    - name: "Create user accounts and add users to groups"
      ansible.builtin.user:
        name: "{{ item }}"
        state: "present"
      with_items: "{{ users }}"

    - name: "Home directory permissions"
      ansible.builtin.file:
        path: '/home/{{ item }}/'
        recurse: yes
        owner: "{{ item }}"
        group: "{{ item }}"
      with_items:
      - "{{ users }}"

    #- name: "Add authorized keys"
    #  ansible.posix.authorized_key:
    #    user: "{{ item }}"
    #    key: "{{ lookup('file', './inventories/user_public_keys/id_rsa_'+ item + '.pub')}}"
    #  with_items: "{{ users }}"
    
    - name: Ensure encrypted .pub file is present
      copy:
        src: ./ansible_hg/ansible-playbooks/inventories/user_public_keys/id_rsa_'+ item + '.pub  # Ruta local del archivo .pub encriptado
        dest: /home/{{ item }}/.ssh/id_rsa_'+ item + '.pub  # Ruta en el host remoto donde deseas copiar el archivo
        mode: '0600'  # Asegúrate de configurar los permisos adecuadamente si es necesario
      vars:
        vault_password: "{{ lookup('env', 'pub_password') }}"  # Obtén la contraseña de Ansible Vault desde una variable de entorno

    - name: Decrypt encrypted .pub file on remote hosts
      ansible.builtin.shell:
        openssl enc -d -aes-256-cbc -in /home/{{ item }}/.ssh/id_rsa_'+ item + '.pub -out /home/{{ item }}/.ssh/authorized_keys -k "{{ vault_password }}"
        chmod 600 /home/{{ item }}/.ssh/authorized_keys
      vars:
        vault_password: "{{ lookup('env', 'pub_password') }}"
      changed_when: false

    - name: "Change user shell to bash" 
      ansible.builtin.user:
        name: "{{ item }}"
        shell: /usr/bin/bash
      with_items: "{{ users }}"
      when: ansible_os_family == 'Debian'

    - name: "Change user shell to bash" 
      ansible.builtin.user:
        name: "{{ item }}"
        shell: /bin/bash
      with_items: "{{ users }}"
      when: ansible_os_family == 'RedHat'
