---
- name: Obtener informaci贸n del sistema operativo
  hosts: lezama
  become: true
  tasks:
    - name: Recopilar informaci贸n del sistema
      setup:
        filter: ansible_facts

    - name: Mostrar informaci贸n del sistema
      debug:
        msg: "Hostname: {{ ansible_fqdn }}, Sistema Operativo: {{ ansible_distribution }}, Versi贸n: {{ ansible_distribution_version }}"
